### ISSUE TITLE
Bad text shadow

### ISSUE THREAD

**Issue by libnova** [stil/gd-text#10]
Hi,

When creating text within a white background, text shadow gets badly shaped (at least for me). To solve it, i rewrote the "Color->getIndex()" function. It works fine for me now:

```php
/**
 * @param resource $image GD image resource
 * @return int Returns the index of the specified color+alpha in the palette of the image,
 *             or -1 if the color does not exist in the image's palette.
 */
public function getIndex($image)
{
	$color = -1;
	if ($this->hasAlphaChannel()) {
		if(($color = imagecolorexactalpha(
			$image,
			$this->red,
			$this->green,
			$this->blue,
			$this->alpha
		)) == -1){
			$color = imagecolorallocatealpha(
				$image,
				$this->red,
				$this->green,
				$this->blue,
				$this->alpha
			);
		}
	} else {
		if(($color = imagecolorexact(
			$image,
			$this->red,
			$this->green,
			$this->blue
		)) == -1){
			$color = imagecolorallocate(
				$image,
				$this->red,
				$this->green,
				$this->blue
			);
		}
	}
	return $color;
}
```

### Before ###
![thumb_bad](https://cloud.githubusercontent.com/assets/12556755/10342038/8836e40a-6d17-11e5-94e1-75ef9861c488.jpg)

### After ###
![thumb_ok](https://cloud.githubusercontent.com/assets/12556755/10342045/8ba1d050-6d17-11e5-8052-4494c80aa370.jpg)

**Comment by stil** [comment]
It seems that images other that True Color are affected (ie. GIFs or PNG-8). Thanks for pointing it out, I will fix it soon.
