### ISSUE TITLE
Use code in a basic php

### ISSUE THREAD

**Issue by AngelSamuel** [stil/gd-text#11]
Hello,

How could I use this code in a basic PHP? I just want to use a form to put name and author and generated.

I had copied and pasted the code into a new .php but apparently this code needs a framework for living.

I just want to use it for a very basic code , how can I use it?

A greeting,
Angel.

**Comment by stil** [comment]
You need to install library via [Composer](https://getcomposer.org/). It's not a framework, just a tool to quickly install external libraries.

**Comment by AngelSamuel** [comment]
Hello,

I fail to understand how it works the library. You say it's a library that allows to work but then where is the autoload.php where you include include (' ../ vendor / autoload.php ' ) file.

Excuse me , I'm a little new to the GD of images and not to use it. Could you show me a code and fully functioning ? I'm not saying put it with the form , just enough , I will pass the text or parameters.

A greeting,
Angel.

**Comment by stil** [comment]
`autoload.php` is automatically generated by Composer. Just read on how Composer works and you'll be fine.
