### ISSUE TITLE
Can I add Font Styles like Bold,Italic or give it some Stroke 

### ISSUE THREAD

**Issue by premreddyn** [stil/gd-text#12]
Great library.Keep it up . I am using it on our site.Very Helpful.Can I add Font Styles like Bold,Italic or give it some Stroke.

**Comment by stil** [comment]
If you need different styles like Bold or Italics, use appropriate font files. For example, Arial font has different styles in separate files:
* arial.ttf - default
* arialbd.ttf - bold
* arialbi.ttf - italic

Unfortunately, we currently don't have a stroke option. If you feel that it's important, please open new issue, so we discuss it here.
