### ISSUE TITLE
Clarity missing on text after the image

### ISSUE THREAD

**Issue by premreddyn** [stil/gd-text#14]
When I am drawing I'm getting a blur(2%) or less clarity text on the image.I checked the ttf and it seems good.Please reply ASAP.
![18ptyxv](https://cloud.githubusercontent.com/assets/5550542/11823183/b6887dde-a398-11e5-8afc-cbf00a6860d5.jpg)
![gg6zn1o](https://cloud.githubusercontent.com/assets/5550542/11823184/b6bf4d32-a398-11e5-961c-2927452b978d.jpg)

**Comment by premreddyn** [comment]
![screenshot from 2015-12-16 02 02 39](https://cloud.githubusercontent.com/assets/5550542/11823277/34f6f8c6-a399-11e5-9af1-335f32618a07.png)
![Uploading Screenshot from 2015-12-16 02:03:11.png…]()

**Comment by stil** [comment]
It seems like font related issue. Change the font you're using and it should be fine.
