### ISSUE TITLE
 imageftbbox(): Could not set character size 

### ISSUE THREAD

**Issue by Brushez** [stil/gd-text#23]
imageftbbox(): Could not set character size some of fonts when i test them 

error line `        return imageftbbox($this->getFontSizeInPoints(), 0, $this->fontFace, $text);
`

**Comment by stil** [comment]
It might be font issue unrelated to gd-text library. Can you provide fonts that cause errors?

**Comment by Brushez** [comment]
i don't know which font actually because i'm calling random posts for every time i refresh the page

**Comment by stil** [comment]
It's very likely that your code has a bug. Are you sure you're setting correct font size every time?
I need a minimal code sample to reproduce your problem and confirm this issue exists.

**Comment by stil** [comment]
Due to no feedback and being unable to reproduce problem, I'm closing this issue.
