### ISSUE TITLE
Can't installing via composer

### ISSUE THREAD

**Issue by dhistira** [stil/gd-text#33]
Problem 1:   
 - The requested package stil/gd-text No version set (parsed as 1.0.0) is satisfiable by stil/gd-text[No version set (parsed as 1.0.0)] but these conflict with your requirements or minimum-stability.

I'm running on WAMP, apache 2.4.23, php 7.0.10. Any ideas?

**Comment by stil** [comment]
Can you please paste your `composer.json` file?

**Comment by dhistira** [comment]
```
{
    "name": "stil/gd-text",
    "description": "A class drawing multiline and aligned text on pictures. Uses GD extension.",
    "license": "MIT",
    "require": {
        "php": ">=5.3",
        "ext-gd": "*",
        "phpunit/phpunit": "6.2"
    },
    "require-dev": {
    },
    "autoload": {
        "psr-4": {
            "GDText\\": "src/",
            "GDText\\Tests\\": "tests/"
        }
    }
}

```

**Comment by stil** [comment]
Firstly, it's not your `composer.json`, you pasted project's `composer.json` instead.

To install `stil/gd-text` follow those steps:
1. Make sure you have Composer installed. Composer is used to manage PHP libraries.
2. Open console window and navigate to your project directory.
3. Type following command to install `stil/gd-text`:
```bash
composer require stil/gd-text
```

If you see output similiar to this:
```
Using version ^1.1 for stil/gd-text
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 1 install, 0 updates, 0 removals
  - Installing stil/gd-text (v1.1.0): Downloading (100%)         
Writing lock file
Generating autoload files
```

it means it successfully has been installed.

**Comment by dhistira** [comment]
Thanks! It works now just by re-installing it
