### ISSUE TITLE
setLeading() doesn't exist

### ISSUE THREAD

**Issue by craigymunro** [stil/gd-text#4]
Hiya,

I noticed the examples in the README reference a ```setLeading()``` method, but it looks like that method doesn't actually exist. Are you planning to implement it?

Cheers, Craig

**Comment by alexarno** [comment]
I think you might be able to do what you need with setLineHeight() ?

It might be that the setLeading() method was refactored to setLineHeight() at some point.

**Comment by craigymunro** [comment]
Aah, well spotted!
