### ISSUE TITLE
Last line different alignment?

### ISSUE THREAD

**Issue by marcusds** [stil/gd-text#6]
I want to have a block of text center vertically and horizontally, and then after it a line that is right aligned, is this possible?

**Comment by stil** [comment]
It's impossible with public API, but you can easily hack the code.
Look there: https://github.com/stil/gd-text/blob/master/src/Box.php#L228-L231
In foreach you can add simple check if `$line` is the line you want to right align. Then explicitly supply switch with `$alignX = "right";`.

I hope I helped.

**Comment by marcusds** [comment]
Yeah, figured something like that out myself. Thanks!
