### ISSUE TITLE
New feature: background color

### ISSUE THREAD

**Issue by liviucmg** [stil/gd-text#8]
Since we already have a drawFilledRectangle method, this is pretty trivial to do. :) Will make a PR soon.

**Comment by JeffersonFilho** [comment]
There is any way that you can add border to the text's as well?

**Comment by petrospap** [comment]
any progress on this?
btw: thanks for this script you save my life :)

**Comment by stil** [comment]
Looks good, thanks for commit.

**Comment by liviucmg** [comment]
@petrospap Glad you found it useful. :) I needed it for a client project, and figured I might as well do a PR.

@stil Thank you as well! :beers:

**Comment by petrospap** [comment]
Thanks dude, working fine! although the new gt-text cant make it work
I use it in https://simply4all.net/mention/ to make cards from tweets
and in https://simply4all.net/pop-corn/ to make cover photos for facebook
keep it up!
